name: khata_pro
description: Mummy Ka Khata PRO 2026 - Advanced
publish_to: 'none'
version: 2.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  speech_to_text: ^7.4.0
  google_fonts: ^8.1.0
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  share_plus: ^10.2.1
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  pdf: ^3.10.7
  printing: ^5.13.0
flutter:
  uses-material-design: true
